### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by martinbuberl** [trustpilot/slack-trustpilot#10]
Releases should be created and tagged here:
https://github.com/trustpilot/slack-trustpilot/releases

**Comment by miklosaubert** [comment]
Created v1.0.0 manually (I'm not sure it's worth investigating an automated process?)

**Comment by martinbuberl** [comment]
@miklosaubert AFAIK we have an automated process for .NET releases - if you feel for it, something automated could be nice but it's not important.
